### ISSUE TITLE
Self hosted install - tinybird

### ISSUE THREAD

**Issue by mikegapinski** [aptabase/aptabase#22]
I am trying to deploy aptabase on my own infra next to sentry for my open source project - https://github.com/tesla-android

I managed to get through the install, created a compose project that spins up a working instance that with Traefik as a reverse proxy.

There are no instructions on tinybird configuration sadly, I pasted the correct token and the default base url but I am getting 403 errors from the NET app. I expect that there is some kind of a configuration required in tinybird after you create the account. 

Thank you so much for open sourcing the project, I'd be happy to contribute a full install guide for the self hosted variant once I solve this issue. 

May I ask why you've chosen to rely on the external db service? I have a feeling you'd be better off with something more open, at least for the OSS variant. My C# is rusty, but I might be willing to try to integrate a tinybird alternative if it makes any sense.

**Comment by goenning** [comment]
Hey Michał, 

You're the first (that I'm aware of) to be self hosting, your input on the docs would help me a lot!

1. On Tinybird, have you created a new token and assigned read/write permissions to the events data source?

2. Tinybird is built on top of clickhouse, which is open source. It's fully managed, cost effective, highly available, etc, etc, which makes it a great option for storing a large amount of data without having to worry about managing a clickhouse cluster.

However, I'm being very careful with how I'm using it because I want to offer clickhouse as an alternative storage for analytics data, which means you could self-host everything, without any external dependency.

There's an `IQueryClient` and `IIngestionClient` interfaces which should have its own ClickHouse implementation as the only difference between TB/CH (from this project's perspective) is the network interface and the schema definition. All queries should work on both TB/CH without any change

**Comment by goenning** [comment]
This should be all you need.

```
cd etc/tinybird
tb auth
tb push datasources/events.datasource
```

There's also a `pipes/billing_usage_v1.pipe` but that's not needed for self hosting.

**Comment by mikegapinski** [comment]
We have liftoff. I'll get the install guide ready soon(traefik with letsencrypt for ssl, easy to monitor with prometheus), I'll test if everything works fine first. 

<img width="1160" alt="image" src="https://github.com/aptabase/aptabase/assets/930055/22ac258b-47ec-4821-8736-dd5f5df5bcb2">

**Comment by goenning** [comment]
Awesome, that's great news! 🚀

A few notes:
1. The latest version has dark mode and removes that Support/Feedback from selfhosted :)
2. When you write that guide, what you think of keeping what's non-essential to an "Advanced Guide" or something like that? Prometheus for instance, is a nice to have but not really needed.

**Comment by mikegapinski** [comment]
@goenning Sure. I have a basic compose config just for this one service

**Comment by goenning** [comment]
I just realised we need to do this https://github.com/aptabase/aptabase/issues/11 to get Country/Region info on self hosted installations. Open to sugestions on a free geo database to use if you know any.

**Comment by mikegapinski** [comment]
I did not even notice that. Something like https://github.com/geoacumen/geoacumen-country would work fine. Free and "good enough".

I have not checked how the app will behave if I were to inject the country code in the payload coming from the client. It should not use the geoip database in this instance. 

My use case is unique, the webapp has constant location access with 1s intervals. I can just decorate the events with this data. I would just get the country / region based on the bbox of the coordinates. I am not going to add any sensitive data, just a bare minimum to figure out the country & firmware versions of their cars(example: https://github.com/tesla-android/flutter-app/commit/e764e0187f29f44903d3046f28d8fbbe1c19a869). That is why my app is fully open and I have not collected any analytics for the previous year 18 months.

I've seen that the flutter plugin does not have offline event tracking yet, a lot of Tesla Android users do not have constant internet access so I'll be implementing this functionality soon. 

Do you have any preferences on how it should work? I was thinking of something like this:
1. Some interaction triggers an event
2. The request to the backend fails
3. The failed event is stored into a local db like hive
4. When the next event is sent and we get a 200 the plugin will start pushing those old events one by one and removes them from the local db.

If you have another idea for it let me know, I'll adjust the flow. I also think the offline event queue should be configurable(like host is now)

**Comment by goenning** [comment]
There are two client features that I think should be implemented at the same time: batch ingestion and offline support, because I think there's a lot of synergy between these two.

The batch event ingestion endpoint will be implemented in the next couple of weeks.

With this endpoint we could make the SDKs push events on a defined interval. So every trackEvent call simply enqueues the event and a background thread flushes the events every X seconds (configurable on init).

In case of failure, it could simply try again all events on next tick.

The tricky part here is what to do when the app closes. I was hoping we could flush on app close and then if that fails, we store the events in disk so it'll be retried on a future reopen. But I guess the implementation really depends on what each platform allow us to do.

What you think?

**Comment by mikegapinski** [comment]
The flush on app closure is a no-go in my opinion. Having to rely on native apis and background refresh for something like this is not worth it and is not a common practice.

A "nice" and easy solution would only need one interceptor on the API client. I'd just flush the old events the moment we get a 200 from any requests to the backend. This covers the "offline mode" and it can be implemented in the exact same way on all platforms. Flutter, Android, iOS, React Native etc. 

The batch ingestion API endpoint would be nice to have but it does not block 90% of the implementation on the client side.

**Comment by goenning** [comment]
I remember reading that Google and Apple recommend minimising the amount of network requests to save battery, which is why I think most other other analytics / error tracking solutions went down this path.

Maybe we don't need to go native if we used a Timer in dart? That way we stay 100% dart and it would work on other platforms like Windows / Web.

**Comment by eeshvardasikcm** [comment]
> I remember reading that Google and Apple recommend minimising the amount of network requests to save battery, which is why I think most other other analytics / error tracking solutions went down this path.
> 
> Maybe we don't need to go native if we used a Timer in dart? That way we stay 100% dart and it would work on other platforms like Windows / Web.

Thanks for inviting me to give feedback. I would require a self hosted install. I like Firebase for my solution at this point. Because you invited me, I will keep watching this self hosted install issue and if anything comes to mind, I will definitely share my thoughts. Maybe getting involved a little with aptabase will change my mind. You never know.

I don't currently use Dart. Please don't let me interrupt too much. It appears you already have a good plan in place for now on self hosted install.
