### ISSUE TITLE
Remove the min height on cards

### ISSUE THREAD

**Issue by darcyvoutt** [aptabase/aptabase#25]
Loving the application but really dislike how there is a `min-h-[28rem]` placed on the card container forcing the sections to be tall even when very little data. It means the lower two grid elements I don't see without scrolling.

What I would suggest is that within:
`webapp/pkg/primitives/Card.tsx`

We remove the `min-h-[28rem]` from `line 18`, so it would go from this:

```
"flex flex-col min-h-[28rem] bg-background p-4",
```

To this:

```
"flex flex-col bg-background p-4",
```

Just think this would be a better user experience.

**Comment by goenning** [comment]
Hey, thanks for the suggestion.

I played with a few different settings and I think it has to have *some* min-height, but it doesn't have to be as much as today.  I reduced it to 12rem, which is equivalent to 3 rows. 

Does it look better now?

On a side note: I also dislike the scrolling inside cards, especially on mobile because you get this double scroll. I'm thinking of limiting to 10 (?) rows and add a "see more" that expands the card.

**Comment by darcyvoutt** [comment]
@goenning looks better and I agree with you on the mobile part with scrolling. Yeah, that's a sound approach on the see more aspect. Not sure if I plan to do that only for mobile, but that would also work for desktop. 

Instead of defining any `min` or `max` heights, you could let the card heights grow with content, but like you say limit the content to 10 and then let the user expand, and have the cards expand in user action.
