### ISSUE TITLE
Display unformatted number of events/users/sessions

### ISSUE THREAD

**Issue by goenning** [aptabase/aptabase#67]
We currently format large numbers to `1.5k` for example, but we should have an option to show the actual number unformatted, maybe on a tooltip?

**Comment by prajwalkulkarni** [comment]
The session values are rendered as percentage values, right? Upto how many decimals are we supposed to show on hover in the tooltip?

**Comment by goenning** [comment]
No, the percentages are fine as it's. What we need to do is a tooltip on these `18.2k` numbers that expand to something like`18.240`

Would you be interested in contributing?

![image](https://github.com/aptabase/aptabase/assets/94755/2eafc4a6-ee47-419c-8538-34b100ef410f)

**Comment by prajwalkulkarni** [comment]
I initially assumed the same, but since you'd mentioned `sessions` in the issue title, I wanted to confirm the same. 

Yes, I'd be interested in contributing, but I'm facing some roadblocks and I was wondering if you could help me here.
1. I set up the project on GitHub codespaces (as setting up the project locally was a little time-consuming and I had to install `.NET` manually). Since I'm running the application on codespaces, It serves the application on a URL that is not `localhost` hence the user registration was failing. I did change the `BASE_URL` but It is still failing. Nonetheless, I created an account from the production application to look for the issue that needed to be solved, but since I was not using the SDK on any application, the dashboard was hidden with an overlay. So I wanted to know if there are any test accounts that I could use for the same?

2. I was going through the codebase and I did notice there's a `Tooltip` component implemented from `@radix-ui/react-tooltip` but from what I understood, we'll have to be implementing it as a compound component `<Tooltip.Provider><Tooltip.Content>xyz</Tooltip.Content><Tooltip.Trigger>xyz</Tooltip.Trigger></Tooltip.Provider>` (kindly correct me if I'm wrong here). I was wondering if we can instead use the tooltip component from `@radix-ui/theme`?

**Comment by goenning** [comment]
1. I haven't tried running it on codespaces, so I'm not sure how to make it work there. I'd recommend running locally, installing .net is pretty straightfoward
2. I'd suggest you use the existing Tooltip component (which extends radix-ui) so you get the existing design for it

**Comment by prajwalkulkarni** [comment]
I was able to setup the project locally, but looks like there's some issue with the registration API. Attaching screenshots for reference.
![404](https://github.com/aptabase/aptabase/assets/22348265/1806924a-09c3-49b6-b88a-3e00af4b9556)
![console](https://github.com/aptabase/aptabase/assets/22348265/da2ef42a-ba81-4abe-95e4-4185b58721e2)

**Comment by prajwalkulkarni** [comment]
I'm not receiving the magic link on my email either (checked spam as well) when trying to register.

**Comment by goenning** [comment]
are you following this guide https://github.com/aptabase/aptabase/blob/main/CONTRIBUTING.md ?
there's a note about emails

**Comment by prajwalkulkarni** [comment]
My bad. I hadn't noticed that! It's working now.
