### ISSUE TITLE
Event data is truncated

### ISSUE THREAD

**Issue by johnrhampton** [aptabase/aptabase#70]
Hi - I am new to aptabase and using it within a React Native App. I noticed that when viewing events within the dashboard and even when exporting to CSV the event data is being truncated with an ellipsis. This makes it difficult to fully understand the event data.

Apologies if I am missing anything - is there a way to view the full event data? Unfortunately, this is going to make it difficult for us to use aptabase. Any help would be greatly appreciated! 

Happy to provide any other information that would help out. Thanks! 

**Snippet from CSV Export**

` The request signature we calculated does not match the s...""`

**Dashboard Screenshot**

<img width="548" alt="image" src="https://github.com/aptabase/aptabase/assets/3935239/f2184f97-6b4a-49ac-8e84-dcca8bb4af64">

**Comment by goenning** [comment]
Hi John, that’s as designed. I think we crop text properties at 180 (needs confirmation). 

I’m optimising Aptabase to aggregate large amount of data, which doesn’t work well with long texts. 

It seems like you’re using it to track errors right? While Aptabase is not designed for error/crash analytics, it *can* be used within that limitation.

What you can do in your case is parse the XML response and send each property individually because cropping happens at the property level.

{ code: “”, message: “”, details: “” }

That’s what I do on my apps as a minimalist approach to error logging.

Alternatively, you might want to consider something like Sentry which is purposefully built for that.

**Comment by johnrhampton** [comment]
Hi @goenning, thanks for the response and context around the text limits! 

We are planning to use aptabase for more typical event tracking but also for tracking errors and happened to notice the truncation on that long error last night.

Thanks for the suggestion about individual properties.

Closing this issue as now we understand they _why_ behind this. Thanks again!
